name: json_web_token
version: 0.0.1
author: George Moschovitis <george.moschovitis@gmail.com>
description: JSON Web Token.
homepage: https://github.com/gmosx/dart-json_web_token
dependencies:
  crypto: any
dev_dependencies:
  unittest: any
