name: jwt
version: 0.0.2
author: George Moschovitis <george.moschovitis@gmail.com>
description: JSON Web Token implemented as a standard Dart codec.
homepage: https://github.com/gmosx/dart-json_web_token
dependencies:
  crypto: any
dev_dependencies:
  unittest: any
